name: drshymaelsayed
favicon: null
layout_spectrum: 0.6679742294363678
typography_spectrum: 0.5317985168658197
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.25032158964313567
  lightness: 0.42373726540245116
  saturation: 0.03926658444106579
  rhythmicContrast: 0.9899732635822147
purpose: []
