name: drshymaelsayed
favicon: null
layout_spectrum: 0.43263
typography_spectrum: 0.5317985168658197
title: Dr. Shyma El Sayed
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e7e5b5'
    - '#929b80'
    - '#894506'
    - '#debc01'
  brandStrength: 0.0625
  lightness: 0.375
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
